/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1.1-148-g8627b7c797-20250912"
#endif /* AVUTIL_FFVERSION_H */
